version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
  deploy-prod:
    docker:
      - image: circleci/node:10.5.0
    steps:
      - checkout
      - run: ssh $DROPLET_USER@$DROPLET_IP "./deploy_project.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-prod:
          filters:
            branches:
              only:
                - master
          requires:
            - build
